geekshop/admins/urls.py
from django.urls import path
from django.views.i18n import set_language

from admins.views import IndexTemplateView, UserCreateView, UserUpdateView, UserDeleteView, UserListView, \
    CategoryListView, CategoryDeleteView, CategoryUpdateView, ProductListView, CategoryCreateView, ProductsUpdateView, \
    ProductsCreateView, ProductsDeleteView

app_name = 'admins'
urlpatterns = [

    path('', IndexTemplateView.as_view(),name='index'),
    path('users/', UserListView.as_view(),name='admin_users'),
    path('users-create/', UserCreateView.as_view(),name='admin_users_create'),
    path('users-update/<int:pk>', UserUpdateView.as_view(),name='admin_users_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(),name='admin_users_delete'),

    path('category/', CategoryListView.as_view(), name='admin_category'),
    path('category/create/', CategoryCreateView.as_view(), name='admin_category_create'),
    path('category-delete/<int:pk>/', CategoryDeleteView.as_view(), name='admin_category_delete'),
    path('category-update/<int:pk>/', CategoryUpdateView.as_view(), name='admin_category_update'),
    # path('category-detail/<int:pk>/', CategoryDetailView.as_view(), name='admin_category_detail'),

    path('product/', ProductListView.as_view(), name='admins_product'),
    path('products-update/<int:pk>/', ProductsUpdateView.as_view(), name='admins_product_update'),
    path('products-create/', ProductsCreateView.as_view(), name='admins_product_create'),
    path('products-delete/<int:pk>/', ProductsDeleteView.as_view(), name='admins_product_delete'),

    path('lang/', set_language, name='set_language'),
]

geekshop/authapp/urls.py
from django.urls import path
# from authapp.views import
from authapp.views import ProfileFormView,LoginListView,RegisterListView,Logout

app_name = 'authapp'
urlpatterns = [

    path('login/', LoginListView.as_view(),name='login'),
    path('register/', RegisterListView.as_view(),name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),

    path('verify/<str:email>/<str:activate_key>/', RegisterListView.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
# from django.views.i18n import set_language

from mainapp.views import index, products

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    # path('language_new/', include('django.conf.urls',namespace='language_new')),
    # path('lang/', set_language, name='language'),
    # path(r'^i18n/', include('django.conf.urls.i18n')),
    # re_path(r'^i18n/', include('django.conf.urls.i18n')),
    
    # re_path('', include('social_django.urls', namespace='social')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/admins/templates/admins/admin-category-read.html
{% extends 'admins/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{ title }}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Категории
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Наименование</th>
                                    <th>Описание</th>
                                    <th>Активный</th>
                                    <th>Удалить</th>
                                    <th>Изменить</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Наименование</th>
                                    <th>Описание</th>
                                    <th>Активный</th>
                                    <th>Удалить</th>
                                    <th>Изменить</th>
                                </tr>
                                </tfoot>
                                <tbody>

                                {% for category in object_list %}
                                    <tr>
                                        <td>{{ category.name }}</td>
                                        <td>{{ category.description }}</td>
                                        <td class="text-center">
                                            {% if category.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}

                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <form action="{% url 'admins:admin_category_delete' category.id %}" method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                                            </form>
                                        </td>
                                        <td>
                                            <a href="{% url 'admins:admin_category_update' pk=category.id %}">
                                                <input class="btn btn-success btn-block" type="submit" value="Изменить">
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_category_create' %}">
                            <button class="btn btn-success">Создать категорию</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>

{% endblock %}

geekshop/admins/templates/admins/admin-product-read.html
{% extends 'admins/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{ title }}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Продукты
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Наименование</th>
                                    <th>Описание</th>
                                    <th>Категория</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Активный</th>
                                    <th>Удалить</th>
                                    <th>Изменить</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Наименование</th>
                                    <th>Описание</th>
                                    <th>Категория</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Активный</th>
                                    <th>Удалить</th>
                                    <th>Изменить</th>
                                </tr>
                                </tfoot>
                                <tbody>

                                {% for product in object_list %}
                                    <tr>
                                        <td>{{ product.name }}</td>
                                        <td>{{ product.description }}</td>
                                        <td>{{ product.category }}</td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.quantity }}</td>

                                        <td class="text-center">
                                            {% if product.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}

                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <form action="{% url 'admins:admins_product_delete' product.id %}"
                                                  method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                                            </form>
                                        </td>
                                        <td>

                                            <a href="{% url 'admins:admins_product_update' product.id %}">
                                                 <input class="btn btn-success btn-block" type="submit" value="Изменить">
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admins_product_create' %}">
                            <button class="btn btn-success">Создать продукт</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>

{% endblock %}

geekshop/admins/templates/admins/admin-products-create.html
{% extends 'admins/base.html' %}
{% load static %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание продукта</h1>
                <form action="{% url 'admins:admins_product_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                {{ form.category }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                            {{ form.price }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                            {{ form.quantity }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                        <div class="col-lg-6">
                            <img width="430" height="100" style="margin-top: 28px"
                                 src="{% static 'vendor/img/products/product_default.png' %}" class="img-thumbnail">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-3" style="margin-top: 33px;">
                            <input class="btn float-lg-right btn-info btn-block btn-lg" type="submit" value="Сохранить">
                        </div>
                        <div class="col-lg-3" style="margin-top: 33px;">
                            <input type="button" class="btn float-lg-right btn-danger btn-block btn-lg"
                                   onclick="window.location.href = '{% url 'admins:admins_product' %}';"
                                   value="Отмена"/>
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-products-update-delete.html
{% extends 'admins/base.html' %}
{% load static %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование продукта | {{ product.name }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admins_product_update' product.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                    {{ form.category }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                      <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                                    {{ form.price }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                                    {{ form.quantity }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                            <div class="col-lg-6">
                                <img width="430" height="100" style="margin-top: 28px"
                                     src="{% if product.image %} {{ product.image.url }} {% else %}{% static 'vendor/img/products/product_default.png' %}{% endif %}" class="img-thumbnail">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6" style="padding-top: 25px">
                                <input class="btn float-lg-right btn-info btn-block btn-lg" type="submit"
                                       value="Сохранить">
                                <input type="button" class="btn float-lg-right btn-danger btn-block btn-lg"
                                       onclick="window.location.href = '{% url 'admins:admins_product' %}';"
                                       value="Отмена"/>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-users-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Пользователи</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Пользователи
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for user in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:admin_users_update' user.id %}"
                                               style="color: dodgerblue">{{ user.username }}</a></td>
                                        <td>{{ user.first_name }}</td>
                                        <td>{{ user.last_name }}</td>
                                        <td>{{ user.email }}</td>
                                        <td class="text-center">
                                            {% if user.is_staff %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}

                                        </td>


                                        <td class="text-center">

                                            {% if user.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_users_create' %}">
                            <button class="btn btn-success">Создать пользователя</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_users_update' user.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                    {{ form.last_name }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.image }}
                                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                        изображение</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя
                                    пользователя</label>
                                {{ form.username }}
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>
                            <div class="col-lg-2">
                                <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                                {{ form.age }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'admins:admin_users_delete' user.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>

{% endblock %}

geekshop/admins/templates/admins/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop - Admin</title>
    <link href="{% static  'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'admins:index' %}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
      <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}

                <input name="next" type="hidden" value="{{ redirect_to }}">
                <div class="form-group row ajax_change" style="margin-top: 10px">
                    <div class="col-md-10">
                        <select class="form-control" name="language">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                        selected{% endif %}>
                                    {{ language.name_local }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-2">
                        <input id='language_site' type="hidden">
                    </div>
                </div>
            </form>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'authapp:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    {% include 'admins/includes/siberia_bar.html' %}
    {% block content %}
    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static  'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static  'js/datatable.js' %}"></script>
<script src="{% static  'js/admins.js' %}"></script>
</body>
</html>